# Numpy Exercise for AI 240  - 10459          

Instructor- Dr. Uma Gajendragadkar




### Save and submit your notebook in your Github account.

### Exercise 1.1 - 
If Numpy is not already installed then please install Numpy using below instruction
!pip install Numpy

In [ ]:
!pip install Numpy

### Exercise 1.2 # Import Numpy package using below instruction 
import numpy as np

In [1]:
import numpy as np

### Exercise 1.3 ## Example Usage Read below example and execute the cell



In [2]:
data = np.array([1,2,3,4,5])

print(data)

print(len(data))

print(type(data))

print(data.shape)



[1 2 3 4 5]
5
<class 'numpy.ndarray'>
(5,)


### Exercise 1.4 Do all exercises from Lecture slides. Refer slides shared after the lecture.

In [3]:
import numpy as np
arr = np.array([10, 20,30, 40, 50])
print(arr)



[10 20 30 40 50]


In [4]:
import numpy as np
arr = np.array([[10, 20, 30], [40, 50,60]])
print(arr)



[[10 20 30]
 [40 50 60]]


In [5]:
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr[0])


10


In [6]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])


[2 3 4 5]


### Exercise 1.5 Searching Arrays - find method of numpy to search an element in array - You can google for the method

Find the indexes where the value is 9:





In [7]:
import numpy as np
arr = np.array([3, 2, 14, 9, 10, 12])
x = np.where(arr == 9)
print(x)

(array([3]),)


### Exercise 1.6 Join two arrays given below and print the result.



In [16]:
import pandas as pd
import numpy as np

arr1 = np.array([9, 5, 8])

arr2 = np.array([55, 89, 76])

df1 = pd.DataFrame(arr1, columns=['A'])
df2 = pd.DataFrame(arr2, columns=['B'])

new_df = df1.join(df2)
print(new_df)

   A   B
0  9  55
1  5  89
2  8  76
